version: '3.8'

services:
    mariadb:
        image: mariadb
        ports:
        - 3307:3306
        environment:
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: product

networks:
  default:
    external: true
    name: api-network_default
